### ISSUE TITLE
Allow installation using Composer by using ComponentInstaller

### ISSUE THREAD

**Issue by holtkamp** [timabell/jquery.stickytabs#2]
It would be great to be able to install Chosen using the [Composer package manager](https://getcomposer.org). For Javascript sources that typically need to be installed in a 'public' folder exposed to the internet, this can be achieved using [ComponentInstaller](https://github.com/RobLoach/component-installer)

Would you guys be open for a PR to support this?

**Comment by timabell** [comment]
Sure, if it would be useful to you.

**Comment by timabell** [comment]
(Though I wouldn't be able to support it as I'm not a PHP dev.)

**Comment by holtkamp** [comment]
Nice, will try to come up with a PR this week. For now I managed to install the master branch using:

```
"repositories": [
        {
            "type": "package",
            "package": {
                "name": "timabell/jquery.stickytabs",
                "type": "component",
                "version": "master",
                "source": {
                    "url": "https://github.com/timabell/jquery.stickytabs.git",
                    "type": "git",
                    "reference": "master"
                },
                "extra": {
                    "component": {
                        "scripts": [
                            "jquery.stickytabs.js"
                        ]
                    }
                },
                "require": {
                    "robloach/component-installer": "*"
                }
            }
        }
    ],
    "require": {
        "timabell/jquery.stickytabs": "*"
    }
```

Instead of pointing to the master branch, a stable '1.0' version would be preferred though, might be something to consider when you review my PR.

**Comment by holtkamp** [comment]
Mmm, I guess this repo would be more appropriate to submit the PR to:
https://github.com/aidanlister/jquery-stickytabs
Closing

**Comment by timabell** [comment]
ah, that wasn't there when I created this repo!
